require "user.options"
require "user.keymaps"
require "user.functions"
require "user.lazy"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.navic"
require "user.comment"
require "user.gitsigns"
require "user.neogit"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.toggleterm"
require "user.project"
require "user.prettier"
require "user.impatient"
require "user.indentline"
require "user.whichkey"
require "user.winbar"
require "user.autocommands"
require "user.ownstuff"
require "user.tmux"
require "user.ts-autotag"
-- require "user.winbar"
